apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-serv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: 10.210.50.29.nip.io
      http:
        paths:
          - path: /api/profile/?(.*)
            pathType: Prefix
            backend:
              service:
                name: profile-serv
                port:
                  number: 3000
